runtime: nodejs18 
handlers:
- url: /(.*)/(.*\..+)$
  static_files: build/\2
  upload: build/\2
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html