runtime: nodejs18 
handlers:
- url: /static
  secure: always
  static_dir: build/static

- url: /(.*\.(gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|css|js|svg))$
  secure: always
  static_files: build/\1
  upload: build/.*\.(gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|css|js|svg)$

- url: .*
  secure: always
  static_files: build/index.html
  upload: build/index.html