runtime: nodejs18 
handlers:
# MyGeotab section
- url: /myGeotab/guides/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/addIns/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/apiReference/methods/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/apiReference/objects/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/apiReference/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/codeSamples/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# MyAdmin section
- url: /myAdmin/guides/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myAdmin/apiReference/methods/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myAdmin/apiReference/objects/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myAdmin/apiReference/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myAdmin/codeSamples/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myAdmin/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Drive section
- url: /drive/addIns/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /drive/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Hardware section
- url: /hardware/guides/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /hardware/protocolReference/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /hardware/codeSamples/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /hardware/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html