runtime: nodejs18 
handlers:
#myGeotab section
- url: /myGeotab/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/guides/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/addIns/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/apiReference/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/apiReference/methods/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/apiReference/objects/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /myGeotab/codeSamples/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
#myAdmin section
- url: /myAdmin/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /drive/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
- url: /hardware/(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html