var
    entityListTypes = [
        ["Audit", "Audit"],
        ["CustomData", "Custom Data"],
        ["DebugData", "Debug Data"],
        ["Diagnostic", "Diagnostic", "Engine"],
        ["DistributionList", "Distribution List"],
        ["Rule", "Rule", "Exceptions"],
        ["ExceptionEvent", "Exception Event", "Exceptions"],
        ["FaultData", "Fault Data", "Engine"],
        ["DriverChange", "Driver Change Data"],
        ["LogRecord", "Log Record"],
        ["Route", "Route"],
        ["StatusData", "Status Data"],
        ["WorkHoliday", "Work Holiday"],
        ["User", "User"],
        ["Device", "Device"],
        ["WorkTime", "Work Time"],
        ["Zone", "Zone"],
        ["ZoneType", "Zone Type"],
        ["Trip", "Trip"],
        ["EngineType", "Engine Type"],
        ["Source", "Source", "Engine"],
        ["Controller", "Controller"],
        ["FailureMode", "Failure Mode"],
        ["UnitOfMeasure", "Unit of Measurement"],
        ["ParameterGroup", "Parameter Group"],
        ["Group", "Group"],
        ["TextMessage", "Text Message"],
        ["DeviceStatusInfo", "Device Status Information"],
        ["FuelTransaction", "Fuel Transaction"],
        ["DutyStatusLog", "Duty Status Log"],
        ["DVIRLog", "DVIR Log"],
        ["AnnotationLog", "Annotation Log"],
        ["ShipmentLog", "Shipment Log"],
        ["Trailer", "Trailer"],
        ["TrailerAttachment", "Trailer Attachment"]
    ];