export default function customTheme(): Record<string, string>{

    const myCustomTheme : Record<string, string> = {
        lineNumberColor: "#9BE6FF",
        lineNumberBgColor: "#9BE6FF",
        backgroundColor: "#202328",
        textColor: "#9BE6FF",
        substringColor: "#9BE6FF",
        keywordColor: "#9BE6FF",
        attributeColor: "#9BE6FF",
        selectorTagColor: "#9BE6FF",
        docTagColor: "#9BE6FF",
        nameColor: "#9BE6FF",
        builtInColor: "#9BE6FF",
        literalColor: "#9BE6FF",
        bulletColor: "#9BE6FF",
        codeColor: "#9BE6FF",
        additionColor: "#9BE6FF",
        regexpColor: "#9BE6FF",
        symbolColor: "#9BE6FF",
        variableColor: "#9BE6FF",
        templateVariableColor: "#9BE6FF",
        linkColor: "#9BE6FF",
        selectorAttributeColor: "#9BE6FF",
        selectorPseudoColor: "#9BE6FF",
        typeColor: "#9BE6FF",
        stringColor: "#9BE6FF",
        selectorIdColor: "#9BE6FF",
        quoteColor: "#9BE6FF",
        templateTagColor: "#9BE6FF",
        deletionColor: "#9BE6FF",
        titleColor: "#9BE6FF",
        sectionColor: "#9BE6FF",
        commentColor: "#9BE6FF",
        metaKeywordColor: "#9BE6FF",
        metaColor: "#9BE6FF",
        functionColor: "#FF9999",
        numberColor: "#9BE6FF",
      };
    
      return myCustomTheme; 
}